FROM jenkinsci/blueocean:latest
RUN apk update \
    && apk add docker unzip curl python2 make git openssh openssl

# aws-cli
RUN curl "https://s3.amazonaws.com/aws-cli/awscli-bundle-1.16.312.zip" -o "awscli-bundle.zip" \
    && unzip awscli-bundle.zip \
    && ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

# kubectl
RUN curl -LO https://dl.k8s.io/release/v1.20.0/bin/linux/amd64/kubectl \
    && chmod +x ./kubectl \firstjob_master
    && mv ./kubectl /usr/local/bin


ENTRYPOINT /bin/cat 
