apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: python
  name: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python
    spec:
      containers:
      - image: ECR_REPO:BUILD_TAG_SUFFIX-GIT_HASH
        name: docker
        resources: {}
status: {}
